//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FighterGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FighterGame.Resources.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------.
        /// </summary>
        internal static string AppBreaker {
            get {
                return ResourceManager.GetString("AppBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: --.--.----.
        /// </summary>
        internal static string ApplicationReleaseDate {
            get {
                return ResourceManager.GetString("ApplicationReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter Game.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string AppPrepareChoose {
            get {
                return ResourceManager.GetString("AppPrepareChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application doesnt work on this language. Please choose another language..
        /// </summary>
        internal static string AppPrepareFalseLang {
            get {
                return ResourceManager.GetString("AppPrepareFalseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact.
        /// </summary>
        internal static string CharacterArtifactName {
            get {
                return ResourceManager.GetString("CharacterArtifactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string CharacterAttributeArmor {
            get {
                return ResourceManager.GetString("CharacterAttributeArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Damage.
        /// </summary>
        internal static string CharacterAttributeAttackDamage {
            get {
                return ResourceManager.GetString("CharacterAttributeAttackDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Speed.
        /// </summary>
        internal static string CharacterAttributeAttackSpeed {
            get {
                return ResourceManager.GetString("CharacterAttributeAttackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Rate.
        /// </summary>
        internal static string CharacterAttributeCritRate {
            get {
                return ResourceManager.GetString("CharacterAttributeCritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string CharacterAttributeHealth {
            get {
                return ResourceManager.GetString("CharacterAttributeHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your opponent was created.
        /// </summary>
        internal static string CharacterCreatorEnemyFinalText {
            get {
                return ResourceManager.GetString("CharacterCreatorEnemyFinalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating your opponent....
        /// </summary>
        internal static string CharacterCreatorEnemyPreparation {
            get {
                return ResourceManager.GetString("CharacterCreatorEnemyPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a name: .
        /// </summary>
        internal static string CharacterCreatorGetName {
            get {
                return ResourceManager.GetString("CharacterCreatorGetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much do you want spend upgrade points on [{0}]. Remaining [{1}/{2}]: .
        /// </summary>
        internal static string CharacterCreatorGetPoints {
            get {
                return ResourceManager.GetString("CharacterCreatorGetPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your number is not beetween 0 and remaining points..
        /// </summary>
        internal static string CharacterCreatorInvalidRangePoints {
            get {
                return ResourceManager.GetString("CharacterCreatorInvalidRangePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your character has been created.
        /// </summary>
        internal static string CharacterCreatorPlayerResult {
            get {
                return ResourceManager.GetString("CharacterCreatorPlayerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---&gt; Create your character &lt;---.
        /// </summary>
        internal static string CharacterCreatorTitle {
            get {
                return ResourceManager.GetString("CharacterCreatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have any Artifact.
        /// </summary>
        internal static string CharacterDrawArtifactFail {
            get {
                return ResourceManager.GetString("CharacterDrawArtifactFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get... [{0}].
        /// </summary>
        internal static string CharacterDrawArtifactResult {
            get {
                return ResourceManager.GetString("CharacterDrawArtifactResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing an Artifact....
        /// </summary>
        internal static string CharacterDrawArtifactTitle {
            get {
                return ResourceManager.GetString("CharacterDrawArtifactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---&gt; {0} win this duel! &lt;---.
        /// </summary>
        internal static string CharacterFightResult {
            get {
                return ResourceManager.GetString("CharacterFightResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deal {1} damage to {2}.
        /// </summary>
        internal static string CharacterFightSchemat {
            get {
                return ResourceManager.GetString("CharacterFightSchemat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}].
        /// </summary>
        internal static string CharacterPrintSchemat {
            get {
                return ResourceManager.GetString("CharacterPrintSchemat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---&gt; {0} &lt;---.
        /// </summary>
        internal static string CharacterPrintTitle {
            get {
                return ResourceManager.GetString("CharacterPrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer cannot be empty..
        /// </summary>
        internal static string EmptyUserInput {
            get {
                return ResourceManager.GetString("EmptyUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer must be number..
        /// </summary>
        internal static string InvalidNumberInput {
            get {
                return ResourceManager.GetString("InvalidNumberInput", resourceCulture);
            }
        }
    }
}
